ia_cms:
    menu:
        mainMenu:
            payment:
                name: Payment
                icon: icon_document_alt
                childs:
                    gateways:
                        name: Payum Gateways
                        route: ia_payment_gateways_index
                    methods:
                        name: Payment Methods
                        route: ia_payment_methods_index
            cms:
                name: Static Pages
                icon: icon_genius
                childs:
                    list:
                        name: List Pages
                        route: ia_cms_pages_index
                    create:
                        name: Create New Page
                        route: ia_cms_pages_create
                