ia_cms:
    menu:
        mainMenu:
            payment:
                name: Payment
                uri: "javascript:;"
                attributes:
                    iconClass: icon_document_alt
                childs:
                    gateways:
                        name: Payum Gateways
                        route: ia_payment_gateways_index
                    methods:
                        name: Payment Methods
                        route: ia_payment_methods_index
            cms_pages:
                name: Static Pages
                uri: "javascript:;"
                attributes:
                    iconClass: icon_genius
                childs:
                    list:
                        name: List Pages
                        route: ia_cms_pages_index
                    create:
                        name: Create New Page
                        route: ia_cms_pages_create
                        display: false
                    update:
                        name: Edit Page
                        route: ia_cms_pages_update
                        routeParameters:
                          id: int
                        display: false
                        
            cms_taxonomy:
                name: Taxonomy
                uri: "javascript:;"
                attributes:
                    iconClass: icon_genius
                childs:
                    list_vocabularies:
                        name: Vocabularies
                        route: ia_cms_taxonomy_vocabularies_index
                    create_vocabulary:
                        name: Create Vocabulary
                        route: ia_cms_taxonomy_vocabularies_create
                        display: true
                    update_vocabulary:
                        name: Edit Vocabulary
                        route: ia_cms_taxonomy_vocabularies_update
                        routeParameters:
                          id: int
                        display: false
        profileMenu:
            profile:
                name: "My Profile"
                route: ia_users_profile_show
                attributes:
                    iconClass: "fas fa-user mr-2"
            logout:
                name: "Log Out"
                route: app_logout
                attributes:
                    iconClass: "fas fa-power-off mr-2"
            documentation:
                name: "Documentation"
                uri: "javascript:;"
                attributes:
                    iconClass: "fas fa-cog mr-2"
                