sylius_resource:
    
    resources:
        ia_users.users:
            driver: doctrine/orm
            classes:
                model:      App\Entity\UserManagement\User
                interface:  Sylius\Component\Resource\Model\ResourceInterface
                controller: VS\UsersBundle\Controller\UsersCrudController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository      
                