sylius_resource:
    #translation:
        #default_locale: '%locale%'
        #locale_provider: sylius.translation.locale_provider.contextual
        #available_locales_provider: sylius.translation.locales_provider
    resources:
        ia_users.users:
            driver: doctrine/orm
            classes:
                model:      App\Entity\UserManagement\User
                interface:  Sylius\Component\Resource\Model\ResourceInterface
                controller: VS\UsersBundle\Controller\UsersCrudController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository      
                