security:
    encoders:
        App\Entity\UserManagement\User:
            algorithm: argon2i
            
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        default_provider:
            entity:
                class: App\Entity\UserManagement\User
                property: username
    firewalls:
        main:
            pattern:      ^/(?!admin)
            provider:       default_provider
            anonymous: true
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: _username
                password_parameter: _password
                always_use_default_target_path: false
                default_target_path:  /cms/pages
            logout:
                path:   /logout
                target: /login
                invalidate_session: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
      - { path: ^/resetting/send-email, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/resetting/request, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
