vs_application:
    resources:
        settings:
            classes:
                model: App\Entity\Settings
        site_settings:
            classes:
                model: App\Entity\SiteSettings
        taxonomy:
            classes:
                model: App\Entity\Taxonomy\Taxonomy
        taxon:
            classes:
                model: App\Entity\Taxonomy\Taxon
            translation:
                classes:
                    model: App\Entity\Taxonomy\TaxonTranslation
        translation:
            classes:
                model: App\Entity\Translation
                
    menu:
        devMenu:
            devTests:
                name: Developement Tests
                uri: "javascript:;"
                attributes:
                    id: devTests
                childs:
                    #taxonomy_test_products:
                    #    name: Test Taxonomy with Product Categorization
                    #    route: app_test_taxonomy
            appBundle:
                name: Symfony Application Bundle
                uri: "javascript:;"
                attributes:
                    id: appBundle
                childs:
                    settings:
                        name: General Settings
                        route: vs_application_settings_index
                    taxonomy:
                        name: Taxonomy
                        route: vs_application_taxonomy_index
            cmsBundle:
                name: Symfony Cms Bundle
                uri: "javascript:;"
                attributes:
                    id: cmsBundle
                childs:
                    pages:
                        name: Pages
                        route: vs_cms_pages_index
                    categories:
                        name: Categories
                        route: vs_cms_page_categories_index
            usersBundle:
                name: Symfony Users Bundle
                uri: "javascript:;"
                attributes:
                    id: usersBundle
                childs:
                    users:
                        name: Users
                        route: vs_users_users_index

        mainMenu:
            application:
                name: Application Core
                uri: "javascript:;"
                attributes:
                    iconClass: icon_document_alt
                childs:
                    settings:
                        name: General Settings
                        route: vs_application_settings_index
                    taxonomy:
                        name: Taxonomy
                        route: vs_application_taxonomy_index

                        
        profileMenu:
            profile:
                name: "My Profile"
                route: ia_users_profile_show
                attributes:
                    iconClass: "fas fa-user mr-2"
            logout:
                name: "Log Out"
                route: app_logout
                attributes:
                    iconClass: "fas fa-power-off mr-2"
            documentation:
                name: "Documentation"
                uri: "javascript:;"
                attributes:
                    iconClass: "fas fa-cog mr-2"
                
     