vs_application:
    resources:
        site:
            classes:
                model: App\Entity\Site
        settings:
            classes:
                model: App\Entity\Settings
        taxonomy:
            classes:
                model: App\Entity\Taxonomy\Taxonomy
        taxon:
            classes:
                model: App\Entity\Taxonomy\Taxon
            translation:
                classes:
                    model: App\Entity\Taxonomy\TaxonTranslation
        translation:
            classes:
                model: App\Entity\Translation
        logentry:
            classes:
                model: App\Entity\LogEntry
                
    menu:
        devMenu:
            devTests:
                name: Developement Tests
                uri: "javascript:;"
                attributes:
                    id: devTests
                childs:
                    #taxonomy_test_products:
                    #    name: Test Taxonomy with Product Categorization
                    #    route: app_test_taxonomy
                    settings_test_generalization__site_1:
                        name: Test Settings Generalization (Site 1)
                        uri: /settings/test_generalization/1
                    settings_test_generalization__site_2:
                        name: Test Settings Generalization (Site 2)
                        uri: /settings/test_generalization/2
                    page_versions_test_list:
                        name: Test Pege Versions List
                        route: app_test_page_versions_list
                        
            appBundle:
                name: Symfony Application Bundle
                uri: "javascript:;"
                attributes:
                    id: appBundle
                childs:
                    settings:
                        name: General Settings
                        route: vs_application_settings_index
                    taxonomy:
                        name: Taxonomy
                        route: vs_application_taxonomy_index
            cmsBundle:
                name: Symfony Cms Bundle
                uri: "javascript:;"
                attributes:
                    id: cmsBundle
                childs:
                    pages:
                        name: Pages
                        route: vs_cms_pages_index
                    categories:
                        name: Categories
                        route: vs_cms_page_categories_index
            usersBundle:
                name: Symfony Users Bundle
                uri: "javascript:;"
                attributes:
                    id: usersBundle
                childs:
                    users:
                        name: Users
                        route: vs_users_users_index
            usersSubscriptionsBundle:
                name: Symfony Users Subscriptions Bundle
                uri: "javascript:;"
                attributes:
                    id: usersSubscriptionsBundle
                childs:
                    mailchimp_audiences:
                        name: Mailchimp Audiences
                        route: vs_users_subscriptions_mailchimp_audiences_index
                    mailchimp_subscribe:
                        name: Newsletter Subscribe
                        route: app_newsletter_mailchimp_subscribe
                    mailchimp_unsubscribe:
                        name: Newsletter Unsubscribe
                        route: app_newsletter_mailchimp_unsubscribe
                        
            MongoDB:
                name: MongoDB Examples
                uri: "javascript:;"
                attributes:
                    id: mongoDbExamples
                childs:
                    products_index:
                        name: List Products
                        route: app_mongodb_product_index
                    products_create:
                        name: Create New Product
                        route: app_mongodb_product_create
            Cassandra:
                name: Cassandra ODM
                uri: "javascript:;"
                attributes:
                    id: cassandraODM
                childs:
                    products_index:
                        name: List Products
                        route: app_cassandra_product_index
                    products_create:
                        name: Create New Product
                        route: app_cassandra_product_create

        mainMenu:
            external_tools:
                name: External Tools
                uri: "javascript:;"
                attributes:
                    id: menu-virtual-hosts
                    iconClass: "fas fa-project-diagram"
                childs:
                    php_info:
                        name: Php Info
                        uri: "/info.php"
                        attributes:
                            target: '_blank'
            test_menu_menu_builder:
                name: Test Menu Builder
                uri: "%test.parameters_in_menu_builder%"
                attributes:
                    id: menu-test
                    iconClass: icon_document_alt
            site_1:
                name: "Site 1"
                uri: "javascript:;"
                attributes:
                    iconClass: icon_document_alt
                childs:
                    home:
                        name: Home Page
                        route: app_site1_home
            site_2:
                name: "Site 2"
                uri: "javascript:;"
                attributes:
                    iconClass: icon_document_alt
                childs:
                    home:
                        name: Home Page
                        route: app_site2_home
                        
            user_permissions:
                name: "User Permissions"
                uri: "javascript:;"
                attributes:
                    iconClass: icon_document_alt
                childs:
                    page_super_admin:
                        name: Page Only For Super-Admins
                        route: app_page_super_admin_only
                    page_admin:
                        name: Page Only For Admins
                        route: app_page_admin_only
                    page_specific_role_1:
                        name: Page Only For Specific Role 1
                        route: app_page_specific_role_1_only
                    page_specific_role_2:
                        name: Page Only For Specific Role 2
                        route: app_page_specific_role_2_only
  
        profileMenu:
            profile:
                name: "My Profile"
                route: vs_users_profile_show
                attributes:
                    iconClass: "fas fa-user mr-2"
            logout:
                name: "Log Out"
                route: vs_application_logout
                attributes:
                    iconClass: "fas fa-power-off mr-2"
            documentation:
                name: "Documentation"
                uri: "javascript:;"
                attributes:
                    iconClass: "fas fa-cog mr-2"
                
     