vs_cms:
    resources:
        pages:
            classes:
                model: App\Entity\Cms\Page
                controller: App\Controller\VsCms\PagesController    # override default bundle's controller
        page_categories:
            classes:
                model: App\Entity\Cms\PageCategory
                controller: App\Controller\VsCms\PagesCategoryController    # override default bundle's controller
   