vs_users:
    resources:
        users:
            classes:
                model: App\Entity\UserManagement\User
        user_info:
            classes:
                model: App\Entity\UserManagement\UserInfo
     