vs_users:
    resources:
        users:
            classes:
                model: App\Entity\UserManagement\User
        user_info:
            classes:
                model: App\Entity\UserManagement\UserInfo
        user_activity:
            classes:
                model: App\Entity\UserManagement\UserActivity
        user_notification:
            classes:
                model: App\Entity\UserManagement\UserNotification
        reset_password_request:
            classes:
                model: App\Entity\UserManagement\ResetPasswordRequest
                
vs_users_subscriptions:
    resources:
        mailchimp_audiences:
            classes:
                model: App\Entity\UsersSubscriptions\MailchimpAudience
        newsletter_subscriptions:
            classes:
                model: App\Entity\UsersSubscriptions\NewsletterSubscription
