vs_cms_pages:
    resource: "@VSCmsBundle/Resources/config/routing/pages.yml"
    prefix:   /bundles/vs-cms/

vs_cms_images:
    resource: "@VSCmsBundle/Resources/config/routing/images.yml"
    prefix:   /bundles/vs-cms/
