
home:
    path: /
    controller: App\Controller\DefaultController::index
 
ia_users:
    resource: "@IAUsersBundle/Resources/config/routing.yml"
    prefix:   /users_bundle/
 
ia_cms:
    resource: "@IACmsBundle/Resources/config/routing.yml"
    prefix:   /cms
    
ia_payment:
    resource: "@IAPaymentBundle/Resources/config/routing.yml"
    prefix:   /payment

    