# Admin Panel Routes
##########################################
app_home:
    path: /
    controller: App\Controller\Admin\DefaultController::index

# Sites Routes
##########################################
app_site1_home:
    path: /site_1/
    controller: App\Controller\Site_1\DefaultController::index

app_site2_home:
    path: /site_2/
    controller: App\Controller\Site_2\DefaultController::index

