
home:
    path: /
    controller: App\Controller\DefaultController::index

security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /security/
    
app_login:
    path: /login
    controller: App\Controller\AuthController::login
    
app_logout:
    path: /logout
    controller: App\Controller\AuthController::logout

ia_users:
    resource: "@VSUsersBundle/Resources/config/routing/user_management.yml"
    prefix:   /users_bundle/
        