imports:
    - { resource: services/developement.yaml }

parameters:
    lang: 'en'
    locale: 'en_US'
    siteTitle: 'VS Symfony Bundles Developement'
    mailer_user: 'wct@example.com'
    admin_template: 'admin'
    website_template: 'website'
    yaml.parser.class: Symfony\Component\Yaml\Parser
    
services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    #twig.extension.date:
    #    class: Twig_Extensions_Extension_Date
    #    tags:
    #        - { name: twig.extension }
    
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
        autowire: false
        
    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        autowire: false
 
    vs_application.form.type.settings:
        class: VS\ApplicationBundle\Form\GeneralSettingsForm
        tags:
            - { name: form.type }
        arguments: ['%vs_application.model.settings.class%', $pageClass: '%vs_cms.model.pages.class%']
        