imports:
    - { resource: services/developement.yaml }
    - { resource: services/cassandra.yaml }

parameters:
    lang: 'en'
    locale: 'en_US'
    languages:
        en_US: English
        bg_BG: Български
    siteTitle: 'VS Symfony Bundles Developement'
    mailer_user: 'wct@example.com'
    debug.error_handler.throw_at: 1
    #yaml.parser.class: Symfony\Component\Yaml\Parser
    
    vs_app.page.tac: 'vs_app_page_tac'
    #vs_users.login_route: 'app_login'
    vs_users.login_by: 'username'
    vs_users.api_token.domain: '.sbd.lh'
    vs_users.api_token.lifetime: 3600
    
    vs_cms.page_categories.taxonomy_id: 3
    
    vs_app.settings.site_id: 1
    
    test.parameters_in_menu_builder: 'test_parameters_in_menu_builder'


services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }
    
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
        autowire: false
        
    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        autowire: false
        #autowire: true
 
    vs_application.form.type.settings:
        class: VS\ApplicationBundle\Form\SettingsForm
        tags:
            - { name: form.type }
        arguments: ['%vs_application.model.settings.class%', $pageClass: '%vs_cms.model.pages.class%']
        
    ###################################
    # GREAT DEBUGGING
    ###################################
    my_blue_screen:
        class: 'Tracy\BlueScreen'
        properties:
            info:
                - 'environment: %kernel.environment%'

    vasek_purchart.tracy_blue_screen.tracy.blue_screen: '@my_blue_screen'
    
    #############################################################################  
